blank_issues_enabled: false
contact_links:
  - name: Artbees Community Support
    url: https://github.com/artbees/community
    about: Please ask and answer questions here.
  - name: Artbees Security Bug Bounty
    url: https://artbees.github.com/
    about: Please report security vulnerabilities here.
